name: finology
description: A new Flutter project.

publish_to: 'none'

version: 1.0.7+7

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  flutter_bloc: ^8.1.1
  uuid: ^3.0.7
  fluttertoast: ^8.0.9
  image_picker: ^0.8.6
  animations: ^2.0.5
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  lottie: ^1.4.3
  page_transition: ^2.0.9
  percent_indicator: ^4.2.2
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/jsonImage/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

