// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5GbWVRklZHxUWCrm9ZgEQpBSJksuA1Ak',
    appId: '1:684950209020:android:42aaaa1caf647149853279',
    messagingSenderId: '684950209020',
    projectId: 'treasure-b7db0',
    databaseURL: 'https://treasure-b7db0-default-rtdb.firebaseio.com',
    storageBucket: 'treasure-b7db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlfDp263_yqMFKI38ic0owQcjXKZkMrYE',
    appId: '1:684950209020:ios:c61788ec98f5c4ab853279',
    messagingSenderId: '684950209020',
    projectId: 'treasure-b7db0',
    databaseURL: 'https://treasure-b7db0-default-rtdb.firebaseio.com',
    storageBucket: 'treasure-b7db0.appspot.com',
    androidClientId: '684950209020-02orsngmvibi3vstkj1uupon4s1ngiif.apps.googleusercontent.com',
    iosClientId: '684950209020-8i310hc8f3g25rn2ckk9tab99k0nse44.apps.googleusercontent.com',
    iosBundleId: 'com.example.finology',
  );
}
